In [1]:
#import libraries
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [2]:
#Question 1
data , target = load_digits(n_class = 10 , return_X_y = True)

In [3]:
print(data.shape)
print(target.shape)

(1797, 64)
(1797,)


In [4]:
x = pd.DataFrame(data)
y = pd.DataFrame(target)

In [5]:
x.head()

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [6]:
y.head()

0
0  0
1  1
2  2
3  3
4  4

In [7]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1797 entries, 0 to 1796
Data columns (total 64 columns):
0     1797 non-null float64
1     1797 non-null float64
2     1797 non-null float64
3     1797 non-null float64
4     1797 non-null float64
5     1797 non-null float64
6     1797 non-null float64
7     1797 non-null float64
8     1797 non-null float64
9     1797 non-null float64
10    1797 non-null float64
11    1797 non-null float64
12    1797 non-null float64
13    1797 non-null float64
14    1797 non-null float64
15    1797 non-null float64
16    1797 non-null float64
17    1797 non-null float64
18    1797 non-null float64
19    1797 non-null float64
20    1797 non-null float64
21    1797 non-null float64
22    1797 non-null float64
23    1797 non-null float64
24    1797 non-null float64
25    1797 non-null float64
26    1797 non-null float64
27    1797 non-null float64
28    1797 non-null float64
29    1797 non-null float64
30    1797 non-null float64
31    1797 non-null float

In [8]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1797 entries, 0 to 1796
Data columns (total 1 columns):
0    1797 non-null int32
dtypes: int32(1)
memory usage: 7.1 KB


In [9]:
#Question 2
x = pd.DataFrame(StandardScaler().fit_transform(x))

In [10]:
x.head()

0         1         2         3         4         5         6         7   \
0  0.0 -0.335016 -0.043081  0.274072 -0.664478 -0.844129 -0.409724 -0.125023   
1  0.0 -0.335016 -1.094937  0.038648  0.268751 -0.138020 -0.409724 -0.125023   
2  0.0 -0.335016 -1.094937 -1.844742  0.735366  1.097673 -0.409724 -0.125023   
3  0.0 -0.335016  0.377661  0.744919  0.268751 -0.844129 -0.409724 -0.125023   
4  0.0 -0.335016 -1.094937 -2.551014 -0.197863 -1.020657 -0.409724 -0.125023   

         8         9     ...           54        55        56        57  \
0 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
1 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
2 -0.059078 -0.624009    ...     0.259230 -0.209785 -0.023596 -0.299081   
3 -0.059078  1.879691    ...     1.072563 -0.209785 -0.023596 -0.299081   
4 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   

         58        59        60        61        62        63  
0  0.086719  0.208293 -0.366771 -1.146647 -0.505670 -0.196008  
1 -1.089383 -0.249010  0.849632  0.548561 -0.505670 -0.196008  
2 -1.089383 -2.078218 -0.164037  1.565686  1.695137 -0.196008  
3  0.282736  0.208293  0.241430  0.379040 -0.505670 -0.196008  
4 -1.089383 -2.306869  0.849632 -0.468564 -0.505670 -0.196008  

[5 rows x 64 columns]

In [13]:
#Question 3
train_x , test_x , train_y , test_y = train_test_split(final_x , y , test_size = 0.3 , random_state = 43)

In [12]:
#Question 4
#compiled this before comipling the above command of Train_test_split()
pca = PCA(n_components = 20)
pc = pca.fit_transform(x)
final_x = pd.DataFrame(pc)
final_x.head()

0         1         2         3         4         5         6   \
0  1.914217 -0.954499 -3.946047  2.028735 -0.267225  0.530312 -1.415223   
1  0.588983  0.924635  3.924738 -1.779874 -0.993226 -0.675628  1.878400   
2  1.302036 -0.317194  3.023346 -2.043365 -2.081047  0.935791 -1.296316   
3 -3.020763 -0.868770 -0.801775 -2.187046 -0.556506  0.727160  0.959588   
4  4.528963 -1.093467  0.973026 -1.419551 -1.715861  1.430762  1.072402   

         7         8         9         10        11        12        13  \
0  1.495523  0.124702 -0.823074 -0.499764 -0.788530  0.226788 -0.194600   
1  0.556641  1.079966  0.087808 -0.502277  0.640893 -0.053217 -0.391592   
2  1.156638  0.787110 -1.097124  2.194836 -2.311920 -0.563407 -0.994755   
3 -1.382314  0.259953  0.743826 -1.063898  0.493159 -0.173338  1.003846   
4 -0.969106 -1.665034  1.172034 -1.016519 -1.365583 -0.355335 -0.107645   

         14        15        16        17        18        19  
0  0.835830  0.098610  0.194728 -0.111590  0.390535  0.420827  
1 -0.747865 -0.215620 -0.086890 -0.450645  0.542062 -0.072747  
2 -1.168226  0.409048 -0.280170 -0.395967 -1.009099 -1.124998  
3 -0.143168 -1.004283 -0.929386 -0.441416  1.465198  0.312432  
4  0.738984  0.186723 -0.051132 -0.620180  1.497557  1.087117

In [14]:
#Question 5
model = LogisticRegression()
model.fit(train_x , train_y)
pred_y = model.predict(test_x)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
#Question 6
print(accuracy_score(test_y ,pred_y))

0.9351851851851852


In [16]:
print(confusion_matrix(test_y ,pred_y))

[[58  0  0  0  0  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  1  4]
 [ 0  0 43  0  1  0  0  1  0  0]
 [ 0  0  0 38  0  1  0  1  1  0]
 [ 0  1  0  0 54  0  0  1  0  1]
 [ 0  0  0  0  0 54  0  0  0  0]
 [ 0  1  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  1  0  0 54  0  0]
 [ 0  7  0  1  0  2  1  0 53  2]
 [ 0  1  0  1  0  1  0  3  1 56]]


In [17]:
print(classification_report(test_y ,pred_y))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        58
          1       0.78      0.88      0.83        41
          2       1.00      0.96      0.98        45
          3       0.95      0.93      0.94        41
          4       0.96      0.95      0.96        57
          5       0.93      1.00      0.96        54
          6       0.98      0.98      0.98        60
          7       0.90      0.98      0.94        55
          8       0.95      0.80      0.87        66
          9       0.89      0.89      0.89        63

avg / total       0.94      0.94      0.94       540

